# Site settings
title: Joe Tower
email: joe-at-joetower.com
description: "Design. Development. Music. Drupal. Opinions."
baseurl: ""
twitter_username: joeydollaz
github_username: joetower
drupal_username: 615178
dribbble_username: joetower
instagram_username: joetower
google_username: joetower
lastfm_username: georgehower
linkedin_username: joetower
discog_username: joetower

debug: false
development: false

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
exclude: [_site, package.json, Gruntfile.js, .gitignore, node_modules, _config.yml, config.rb, Gemfile, Gemfile.lock,]

navigation:
 - title: Archive
   url: /archive
 - title: About
   url: /about
 - title: Contact
   url: /contact
